name: Download racersbin

on:
  workflow_call:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:

    - name: Restore cached original binaries
      id: cache-original-binaries
      uses: actions/cache/restore@v5
      with:
        enableCrossOsArchive: true
        path: racersbin
        key: racersbin

    - name: Download original racers binaries
      if: ${{ !steps.cache-original-binaries.outputs.cache-hit }}
      run: |
        wget https://legoisland.org/download/LEGORacers.exe --directory-prefix=racersbin
        wget https://legoisland.org/download/GolDP.dll --directory-prefix=racersbin

    - name: Cache original binaries
      if: ${{ !steps.cache-original-binaries.outputs.cache-hit }}
      uses: actions/cache/save@v5
      with:
        enableCrossOsArchive: true
        path: racersbin
        key: racersbin
